version: "3"

services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development

    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=tamas
      - MONGO_PASSWORD=mypassword

    command: npm run dev

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: tamas
      MONGO_INITDB_ROOT_PASSWORD: mypassword
